1.Documentation reading


In [ ]:

# No code solution (reading)

2.Create a random tensor with shape (7, 7).

In [ ]:

#Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size = (7,7))
random_tensor

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

3.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
#create another random tensor
random_tensor2 = torch.rand(size = (1,7))
random_tensor2

#perform matrix multiplication
Tensor = torch.matmul(random_tensor, random_tensor2.T )
Tensor, Tensor.shape

(tensor([[1.6914],
         [1.7581],
         [2.0906],
         [1.8975],
         [1.7585],
         [1.7961],
         [1.8900]]),
 torch.Size([7, 1]))

4.Set the random seed to 0 and do 2 & 3 over again

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor1 = torch.rand(size = (7,7))
random_tensor2 = torch.rand(size = (1,7))

# Matrix multiply tensors
tensor = torch.matmul(random_tensor1, random_tensor2.T)
tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5.Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [ ]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)

6.Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.cuda.is_available()

# Create two random tensors on GPU
tensor_a = torch.rand(2,3).to(device = 'cuda')
tensor_b = torch.rand(2,3).to(device = 'cuda')
tensor_a, tensor_b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7.Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:

# Perform matmul on tensor_A and tensor_B
tensor_a = torch.rand(2,3).to(device = 'cuda')
tensor_b = torch.rand(2,3).to(device = 'cuda')
tensor = torch.matmul(tensor_a, tensor_b.T)
tensor, tensor.shape

(tensor([[0.3803, 0.5159],
         [0.3943, 0.4501]], device='cuda:0'),
 torch.Size([2, 2]))

 8.Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = torch.max(tensor)
max
# Find min
min = torch.min(tensor)
min

tensor(0.3803, device='cuda:0')

9.Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"Index where max value occurs: {tensor.argmax()}")

# Find arg min
print(f"Index where min value occurs: {tensor.argmin()}")



Index where max value occurs: 1
Index where min value occurs: 0


10.Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_2 = tensor_1.squeeze()

# Print out tensors and their shapes
print("Tensor 1:", tensor_1)
print("Shape of Tensor 1:", tensor_1.shape)

print("\nTensor 2:", tensor_2)
print("Shape of Tensor 2:", tensor_2.shape)


Tensor 1: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of Tensor 1: torch.Size([1, 1, 1, 10])

Tensor 2: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of Tensor 2: torch.Size([10])
